"""Scene JSON (docs/07) and the synthetic walls the planner is developed against.

Phase 2 is specified to run on synthetic scenes and swap in CV output later (docs/00 s7). The
walls are generated by Unity's RandomWallGenerator and committed to /walls as Scene JSON -- there
is no generator here, on purpose. Two implementations of the same wall drift, and Scene JSON is
what CV will hand over in Phase 3 anyway, so this side only ever reads.

Re-export from the editor (RandomWallGenerator's "Export walls") after changing anything that
moves holds, and commit the result.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

LIMBS = ("left_hand", "right_hand", "left_foot", "right_foot")
HANDS = ("left_hand", "right_hand")
FEET = ("left_foot", "right_foot")

# What RandomWallGenerator.maxReach is set to: the hand line is built so no two consecutive holds on
# it are further apart than this, and ReachModel.hand_step has to cover it or a wall is unclimbable
# by construction. Only the checks in selftest use it -- if it stops matching the editor, they fail,
# which is the point.
MAX_REACH = 0.7


@dataclass
class Hold:
    id: int
    position: tuple[float, float]  # wall-local metres, origin bottom-left
    color: str = "gray"


@dataclass
class Route:
    id: int
    hold_ids: list[int]
    start_hold_ids: list[int]
    top_hold_id: int


@dataclass
class Scene:
    width: float
    height: float
    holds: list[Hold] = field(default_factory=list)
    routes: list[Route] = field(default_factory=list)

    @property
    def route(self) -> Route:
        return self.routes[0]

    def hold(self, hold_id: int) -> Hold:
        for h in self.holds:
            if h.id == hold_id:
                return h
        raise KeyError(f"no hold {hold_id}")

    def position(self, hold_id: int) -> tuple[float, float]:
        return self.hold(hold_id).position

    def to_dict(self) -> dict:
        return {
            "wall": {"coordinate_system": "wall_local_2d", "width": self.width, "height": self.height},
            "holds": [{"id": h.id, "position": list(h.position), "color": h.color} for h in self.holds],
            "routes": [
                {
                    "id": r.id,
                    "hold_ids": list(r.hold_ids),
                    "start_hold_ids": list(r.start_hold_ids),
                    "top_hold_id": r.top_hold_id,
                }
                for r in self.routes
            ],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Scene":
        return cls(
            width=data["wall"]["width"],
            height=data["wall"]["height"],
            holds=[Hold(h["id"], tuple(h["position"]), h.get("color", "gray")) for h in data["holds"]],
            routes=[Route(**r) for r in data["routes"]],
        )

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), indent=2))

    @classmethod
    def load(cls, path: str | Path) -> "Scene":
        return cls.from_dict(json.loads(Path(path).read_text()))


WALL_DIR = Path(__file__).resolve().parents[2] / "walls"


def wall_paths() -> list[Path]:
    """The exported walls, in filename order. Index, not seed -- the seed lives in Unity."""
    paths = sorted(WALL_DIR.glob("wall_*.json"))
    if not paths:
        raise FileNotFoundError(f"no walls in {WALL_DIR}; export them from Unity (docs/05)")
    return paths


def wall(index: int) -> Scene:
    return Scene.load(wall_paths()[index])
